#!/bin/bash
./gradlew clean shadowDistZip

cp server/build/distributions/server-shadow-0.0.1.zip
# Define the source and destination directories
SOURCE_DIR="server/build/distributions"
DEST_DIR="../"

echo "Start copying the assembly from $SOURCE_DIR to the level of your project directory"
# Find the most recently modified file
LATEST_FILE=$(ls -t "$SOURCE_DIR"/server-*.zip | head -n 1)

# Copy the most recently modified file to the destination directory
cp "$LATEST_FILE" "$DEST_DIR"

echo "Copied $LATEST_FILE to $DEST_DIR"